// SPDX-License-Identifier: MIT
pragma solidity ^0.8.25;

import {Test} from "forge-std/Test.sol";
import {ConfidentialPolicy} from "../src/ConfidentialPolicy.sol";

/// @notice Cross-language commitment check.
///
/// The commitment is computed in TypeScript (browser, at deploy), verified in
/// Solidity (here, at execution), and re-derived in Go (inside the TEE, before
/// signing). Three implementations of one hash is exactly the kind of drift that
/// surfaces as an unexplainable revert during a live demo.
///
/// These vectors are generated by packages/policy and read here verbatim. If
/// this suite fails after someone changes the TypeScript encoder, that is the
/// safety net working -- do not "fix" it by regenerating the fixture.
contract CommitmentVectorsTest is Test {
    struct Vector {
        string name;
        address[] recipients;
        uint256[] amounts;
        bytes32 salt;
        bytes32 expected;
    }

    function _load() internal view returns (Vector[] memory out) {
        string memory raw =
            vm.readFile(string.concat(vm.projectRoot(), "/../policy/fixtures/commitment-vectors.json"));

        uint256 count = 0;
        while (vm.keyExistsJson(raw, string.concat("$[", vm.toString(count), "]"))) {
            count++;
        }

        out = new Vector[](count);
        for (uint256 i = 0; i < count; i++) {
            string memory base = string.concat("$[", vm.toString(i), "]");
            uint256 n = 0;
            while (
                vm.keyExistsJson(
                    raw, string.concat(base, ".distributions[", vm.toString(n), "]")
                )
            ) {
                n++;
            }

            address[] memory recipients = new address[](n);
            uint256[] memory amounts = new uint256[](n);
            for (uint256 j = 0; j < n; j++) {
                string memory d = string.concat(base, ".distributions[", vm.toString(j), "]");
                recipients[j] =
                    vm.parseJsonAddress(raw, string.concat(d, ".recipient"));
                amounts[j] = vm.parseUint(
                    vm.parseJsonString(raw, string.concat(d, ".amount"))
                );
            }

            out[i] = Vector({
                name: vm.parseJsonString(raw, string.concat(base, ".name")),
                recipients: recipients,
                amounts: amounts,
                salt: vm.parseJsonBytes32(raw, string.concat(base, ".salt")),
                expected: vm.parseJsonBytes32(raw, string.concat(base, ".expected"))
            });
        }
    }

    function test_solidityMatchesTypeScriptVectors() public view {
        Vector[] memory vectors = _load();
        assertGt(vectors.length, 0, "no vectors loaded -- run `pnpm vectors`");

        for (uint256 i = 0; i < vectors.length; i++) {
            Vector memory v = vectors[i];

            ConfidentialPolicy.Share[] memory shares =
                new ConfidentialPolicy.Share[](v.recipients.length);
            for (uint256 j = 0; j < v.recipients.length; j++) {
                shares[j] = ConfidentialPolicy.Share({
                    recipient: v.recipients[j],
                    shareBps: uint16(v.amounts[j])
                });
            }

            // Must match ConfidentialPolicy.execute's check exactly.
            bytes32 actual = keccak256(abi.encode(shares, v.salt));

            assertEq(
                actual,
                v.expected,
                string.concat("commitment drift on vector: ", v.name)
            );
        }
    }
}
