[profile.default]
src = "src"
test = "test"
out = "out"
libs = ["lib"]
solc = "0.8.25"
optimizer = true
optimizer_runs = 200
via_ir = false

[rpc_endpoints]
coston2 = "https://coston2-api.flare.network/ext/C/rpc"

[etherscan]
coston2 = { key = "unused", url = "https://coston2-explorer.flare.network/api" }
