#!/usr/bin/env bash
# sync-web-env.sh — write apps/web/.env.local from what is actually deployed.
#
# The web app needs five addresses, and they live in two generated files:
# packages/contracts/deployments/coston2.json (ours, from forge script) and
# apps/extension/config/extension.env (the instruction sender, from the
# extension pre-flight). Copying them across by hand is the step where a
# redeploy silently half-lands -- three addresses updated, one stale, and a
# revert that looks like a code bug.
#
#     pnpm sync-web-env
#
# Idempotent. Safe to run after any redeploy. Never touches a private key: both
# inputs are public addresses, and the extension env is read line-wise for one
# specific variable rather than sourced.

set -uo pipefail

cd "$(dirname "$0")/.." || exit 1

GREEN=$'\033[32m'; RED=$'\033[31m'; YELLOW=$'\033[33m'; DIM=$'\033[2m'; OFF=$'\033[0m'

DEPLOYMENTS=packages/contracts/deployments/coston2.json
EXT_CONFIG=apps/extension/config/extension.env
TARGET=apps/web/.env.local

if [ ! -f "$DEPLOYMENTS" ]; then
  printf '%s✗%s %s not found.\n' "$RED" "$OFF" "$DEPLOYMENTS"
  printf '  %s→ cd packages/contracts && forge script script/Deploy.s.sol --rpc-url coston2 --broadcast%s\n' "$DIM" "$OFF"
  exit 1
fi

get() { jq -r ".$1 // empty" "$DEPLOYMENTS" 2>/dev/null; }

factory=$(get policyFactory)
gate=$(get teeAttestorGate)
heartbeat=$(get manualHeartbeatTrigger)
timestamp=$(get timestampTrigger)
fxrp=$(get fxrp)
block=$(get deployBlock)

sender=""
if [ -f "$EXT_CONFIG" ]; then
  sender=$(grep -E '^INSTRUCTION_SENDER=' "$EXT_CONFIG" | head -1 | sed -E 's/^INSTRUCTION_SENDER=//' | tr -d '"' | tr -d "'")
fi

proxy=""
if [ -f apps/extension/.env ]; then
  proxy=$(grep -E '^EXT_PROXY_URL=' apps/extension/.env | head -1 | sed -E 's/^EXT_PROXY_URL=//' | tr -d '"' | tr -d "'")
fi

cat > "$TARGET" <<EOF
# Generated by scripts/sync-web-env.sh -- do not edit by hand.
# Re-run \`pnpm sync-web-env\` after any redeploy.
#
# Sources:
#   $DEPLOYMENTS
#   $EXT_CONFIG

NEXT_PUBLIC_POLICY_FACTORY=$factory
NEXT_PUBLIC_TEE_ATTESTOR_GATE=$gate
NEXT_PUBLIC_MANUAL_HEARTBEAT_TRIGGER=$heartbeat
NEXT_PUBLIC_TIMESTAMP_TRIGGER=$timestamp
NEXT_PUBLIC_FXRP=$fxrp
NEXT_PUBLIC_FACTORY_DEPLOY_BLOCK=${block:-0}
NEXT_PUBLIC_POLICY_INSTRUCTION_SENDER=$sender
NEXT_PUBLIC_EXT_PROXY_URL=$proxy
EOF

printf '%s✓%s wrote %s\n\n' "$GREEN" "$OFF" "$TARGET"

report() {
  if [ -z "$2" ]; then
    printf '  %s!%s %-28s %s\n' "$YELLOW" "$OFF" "$1" "empty"
  else
    printf '  %s✓%s %-28s %s\n' "$GREEN" "$OFF" "$1" "$2"
  fi
}

report policyFactory "$factory"
report teeAttestorGate "$gate"
report manualHeartbeatTrigger "$heartbeat"
report timestampTrigger "$timestamp"
report fxrp "$fxrp"
report instructionSender "$sender"
report extProxyUrl "$proxy"

printf '\n%sRun pnpm preflight to confirm each address has code on chain.%s\n' "$DIM" "$OFF"
